services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "/usr/local/bin/wait-for-it.sh db:5432 --timeout=30 -- poetry run alembic upgrade head &&
      poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"
