"""edit product

Revision ID: 3af4eb6b4e65
Revises: 79f37eb58d8f
Create Date: 2024-09-20 19:27:18.993488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af4eb6b4e65'
down_revision: Union[str, None] = '79f37eb58d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_type_name', sa.String(), nullable=False))
    op.drop_constraint('product_product_type_id_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'product_type', ['product_type_name'], ['name'])
    op.drop_column('product', 'product_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_product_type_id_fkey', 'product', 'product_type', ['product_type_id'], ['id'])
    op.drop_column('product', 'product_type_name')
    # ### end Alembic commands ###
